### PR TITLE
updated readme

### LINKED ISSUE #10: README needs to be updated
The README needs to contain the info outlined here:
https://github.com/NOAA-EMC/NCEPLIBS/issues/120

### PR DESCRIPTION
**Pull request by edwardhartnett**
Updated README.

Moved docs to docs directory and put them up on gh-pages.

Fixes #10

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA please review so this can be merged.

**Comment by GeorgeGayno-NOAA** [comment]
The user_guide.md file displays with odd formatting in my browser.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA ok stand by while I look...

**Comment by GeorgeGayno-NOAA** [comment]
> The user_guide.md file displays with odd formatting in my browser.

To be more specific, at the bottom, the sample programs are not displaying correctly.   Like the carriage returns are missing.

**Comment by edwardhartnett** [comment]
OK, take a look now...

**Comment by GeorgeGayno-NOAA** [comment]
> OK, take a look now...

That looks better.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Looks good

**Pull request merged**
